sudo: required

language: python
cache:
  - pip

python:
  - 2.7

services:
  - postgresql

env:
  global:
    # These env vars are available to every build
    - PYTHONPATH=$PYTHONPATH:../refinery:../refinery/config
    - DJANGO_SETTINGS_MODULE=config.settings.prod
install:
  - git clone https://github.com/refinery-platform/refinery-platform.git
  - cp tool-annotations/*.json refinery-platform/refinery/tool_manager/visualization_annotations
  - cd refinery-platform
  - pip install -r requirements.txt --quiet
   # Vagrant is not used on travis: This user is just for the database.
  - createuser --createdb --no-superuser --no-createrole vagrant
  - createdb -O vagrant refinery
  - pushd refinery
  # See http://www.stuartellis.eu/articles/erb/#running-erb-from-the-command-line
  - erb config/config.json.erb > config/config.json
  - python manage.py migrate --noinput

script:
  - python manage.py generate_tool_definitions --visualizations